name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          flake8 .
          pytest --maxfail=1 --disable-warnings

  deploy:
    if: github.event_name == 'push'
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Primero configuramos las credenciales AWS para que Zappa pueda encontrar las credenciales
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Solo si usas credenciales temporales
          aws-region: us-east-1

      - name: Create and activate virtual environment, install dependencies and deploy with Zappa
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Asegúrate de que Zappa esté instalado (puedes incluirlo en requirements.txt o instalarlo aquí)
          pip install zappa
          zappa update dev
